drop table WeatherLocation if exists;
drop table Forecast if exists;

create table WeatherLocation (
  weatherLocation_id bigint generated by default as identity (start with 1),
  locationName varchar(255),
  locationType varchar(255),
  country varchar(255),
  timeZone varchar(255),
  altitude varchar(255),
  latitude varchar(255),
  longitude varchar(255),
  primary key(weatherLocation_id)
);

create table Forecast (
  forecast_id bigint generated by default as identity (start with 1),
  weatherLocation_id bigint,
  fromTime varchar(255),
  toTime varchar(255),
  description varchar(255),
  minPrecipitation varchar(255),
  maxPrecipitation varchar(255),
  temperature varchar(255),
  primary key(forecast_id),
  foreign key(weatherLocation_id) references WeatherLocation(weatherLocation_id)
);

insert into WeatherLocation(locationName, locationType, country, timeZone, altitude, latitude, longitude) values('Oslo', 'City', 'Norway', 'Europe/Oslo', '10', '100', '200');
insert into WeatherLocation(locationName, locationType, country, timeZone, altitude, latitude, longitude) values('Ski', 'Suburb', 'Norway', 'Europe/Oslo', '100', '300', '400');
insert into WeatherLocation(locationName, locationType, country, timeZone, altitude, latitude, longitude) values('Skotbu', 'Rural', 'Norway', 'Europe/Oslo', '110', '500', '600');

insert into Forecast(weatherLocation_id, fromTime, toTime, description, minPrecipitation, maxPrecipitation, temperature) values(1, '07.08.2012', '07.08.2012', 'Rainy', '4', '10', '14');
insert into Forecast(weatherLocation_id, fromTime, toTime, description, minPrecipitation, maxPrecipitation, temperature) values(2, '08.08.2012', '08.08.2012', 'Cloudy', '1', '2', '17');
insert into Forecast(weatherLocation_id, fromTime, toTime, description, minPrecipitation, maxPrecipitation, temperature) values(3, '09.08.2012', '09.08.2012', 'Sunny', '0', '0', '22');